name: "Main - PR Label Checker"

on: push

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    name: "Build and push image"
    steps:
      - uses: actions/checkout@v3
      - name: GitHub Action for GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: 17
      - name: docker login
        run: docker login --username tinyangrykitten --password ${{ secrets.DOCKER_TOKEN }}
      - name: Build project
        run: sh buildAndPush.sh
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f build/kubernetes/kubernetes.yml
